--- 
driver: 
   name: vagrant 
provisioner: 
   name: chef_zero 
platforms: 
   - name: centos-7
   - name: centos-8
suites: 
   - name: default 
   run_list: 
      - recipe[my_cookbook_test::default] 
